apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginx-gateway-fabric 
  namespace: flux-system
spec:
  interval: 10m
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/controllers/nginx-gateway-fabric/overlays/staging
  dependsOn:
    - name: gateway-api-crds-bootstrap
    - name: infra-sources-oci

