apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-pvc
  namespace: flux-system
spec:
  interval: 10m
  path: ./infrastructure/storage/claims/open-webui/overlays/staging
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
