apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-dns
  namespace: flux-system
spec:
  interval: 10m
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/controllers/external-dns/overlays/staging
  dependsOn:
    - name: infra-sources-helm
  healthChecks:
    - kind: Deployment
      name: external-dns
      namespace: external-dns
