apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: flux-system
spec:
  chart:
    spec:
      version: 1.18.0
  values:
    fullnameOverride: external-dns
    provider: google
    sources:
      - gateway-httproute
      - gateway-grpcroute
    logLevel: debug
    domainFilters:
      - tunedev.xyz
    txtOwnerId: external-dns-staging
