apiVersion: v1
kind: Secret
metadata:
  name: external-dns-azure
  namespace: external-dns
type: Opaque
stringData:
  azure.json: |
    {
      "tenantId": "5bd9cf2d-0241-4846-8d13-6ce59c689cc5",
      "subscriptionId": "2329876a-dd1e-4d17-9d7e-6504024dd500",
      "resourceGroup": "dns-rg-30125",
      "useWorkloadIdentityExtension": true
    }